/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enpresa.productadmin.vistas;

/**
 *
 * @author Alejo
 */
public class BitacoraAcceso extends javax.swing.JPanel {

    /**
     * Creates new form BitacoraAcceso
     */
    public BitacoraAcceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBitacoraA = new javax.swing.JTable();
        paFiltrar = new javax.swing.JPanel();
        txtHastaDia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHastaMes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDeDia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDeMes = new javax.swing.JTextField();
        txtDeHora = new javax.swing.JTextField();
        txtDeAño = new javax.swing.JTextField();
        txtHastaHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cBoxFecha = new javax.swing.JCheckBox();
        txtHastaAño = new javax.swing.JTextField();
        cBoxHora = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        cBoxUsuario = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(980, 505));
        setLayout(null);

        tbBitacoraA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fecha", "Hora", "Usuario"
            }
        ));
        tbBitacoraA.setToolTipText("");
        tbBitacoraA.setPreferredSize(new java.awt.Dimension(578, 448));
        jScrollPane1.setViewportView(tbBitacoraA);

        add(jScrollPane1);
        jScrollPane1.setBounds(16, 41, 578, 448);

        paFiltrar.setBorder(javax.swing.BorderFactory.createTitledBorder("¿Filtrar?"));
        paFiltrar.setLayout(null);

        txtHastaDia.setPreferredSize(new java.awt.Dimension(30, 22));
        paFiltrar.add(txtHastaDia);
        txtHastaDia.setBounds(70, 105, 30, 22);

        jLabel1.setText("De:");
        paFiltrar.add(jLabel1);
        jLabel1.setBounds(17, 65, 17, 16);

        txtHastaMes.setPreferredSize(new java.awt.Dimension(30, 22));
        paFiltrar.add(txtHastaMes);
        txtHastaMes.setBounds(106, 105, 30, 22);

        jLabel2.setText("Hasta:");
        paFiltrar.add(jLabel2);
        jLabel2.setBounds(16, 108, 33, 16);

        jLabel7.setText("De:");
        paFiltrar.add(jLabel7);
        jLabel7.setBounds(235, 65, 17, 16);

        txtDeDia.setPreferredSize(new java.awt.Dimension(30, 22));
        paFiltrar.add(txtDeDia);
        txtDeDia.setBounds(71, 62, 30, 27);

        jLabel8.setText("Hasta:");
        paFiltrar.add(jLabel8);
        jLabel8.setBounds(234, 108, 33, 16);

        txtDeMes.setPreferredSize(new java.awt.Dimension(30, 22));
        paFiltrar.add(txtDeMes);
        txtDeMes.setBounds(107, 62, 30, 27);

        txtDeHora.setPreferredSize(new java.awt.Dimension(50, 22));
        paFiltrar.add(txtDeHora);
        txtDeHora.setBounds(288, 62, 50, 27);

        txtDeAño.setPreferredSize(new java.awt.Dimension(50, 22));
        paFiltrar.add(txtDeAño);
        txtDeAño.setBounds(143, 62, 50, 27);

        txtHastaHora.setPreferredSize(new java.awt.Dimension(50, 22));
        paFiltrar.add(txtHastaHora);
        txtHastaHora.setBounds(288, 105, 50, 27);

        jLabel3.setText("/");
        paFiltrar.add(jLabel3);
        jLabel3.setBounds(101, 65, 5, 16);
        paFiltrar.add(jSeparator1);
        jSeparator1.setBounds(21, 147, 314, 10);

        jLabel4.setText("/");
        paFiltrar.add(jLabel4);
        jLabel4.setBounds(137, 65, 5, 16);

        cBoxFecha.setText("Fecha");
        paFiltrar.add(cBoxFecha);
        cBoxFecha.setBounds(17, 30, 54, 20);

        txtHastaAño.setPreferredSize(new java.awt.Dimension(50, 22));
        paFiltrar.add(txtHastaAño);
        txtHastaAño.setBounds(142, 105, 50, 22);

        cBoxHora.setText("Hora");
        paFiltrar.add(cBoxHora);
        cBoxHora.setBounds(234, 30, 49, 20);

        jLabel5.setText("/");
        paFiltrar.add(jLabel5);
        jLabel5.setBounds(100, 108, 5, 16);

        cBoxUsuario.setText("Usuario");
        paFiltrar.add(cBoxUsuario);
        cBoxUsuario.setBounds(51, 176, 63, 20);

        jLabel6.setText("/");
        paFiltrar.add(jLabel6);
        jLabel6.setBounds(136, 108, 5, 16);

        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 22));
        paFiltrar.add(txtUsuario);
        txtUsuario.setBounds(153, 174, 150, 27);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        paFiltrar.add(btnBuscar);
        btnBuscar.setBounds(102, 217, 150, 50);

        add(paFiltrar);
        paFiltrar.setBounds(610, 41, 354, 448);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox cBoxFecha;
    private javax.swing.JCheckBox cBoxHora;
    private javax.swing.JCheckBox cBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel paFiltrar;
    private javax.swing.JTable tbBitacoraA;
    private javax.swing.JTextField txtDeAño;
    private javax.swing.JTextField txtDeDia;
    private javax.swing.JTextField txtDeHora;
    private javax.swing.JTextField txtDeMes;
    private javax.swing.JTextField txtHastaAño;
    private javax.swing.JTextField txtHastaDia;
    private javax.swing.JTextField txtHastaHora;
    private javax.swing.JTextField txtHastaMes;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
