package com.enpresa.productadmin.vistas.gui;

import com.enpresa.productadmin.modelo.dto.DTO;
import com.enpresa.productadmin.modelo.dto.RegistroAccesoBusquedaDTO;
import com.enpresa.productadmin.vistas.EntradaUsuario;
import com.enpresa.productadmin.vistas.MostrarRegistros;
import com.enpresa.productadmin.vistas.VistaGraficaConRegistros;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Alejo
 */
public class BitacoraAccesoVista extends VistaGraficaConRegistros implements EntradaUsuario, MostrarRegistros {

    /**
     * Creates new form BitacoraAcceso
     */
    public BitacoraAccesoVista() {
        initComponents();
        agregarAlternadores();
    }
    
    private void agregarAlternadores() {
        cBoxFecha.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxFecha.isSelected();
            txtFechaInicial.setEnabled(enabled);
            txtFechaFinal.setEnabled(enabled);

            txtFechaInicial.setText("");
            txtFechaFinal.setText("");
        });

        cBoxHora.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxHora.isSelected();
            txtHoraInicial.setEnabled(enabled);
            txtHoraFinal.setEnabled(enabled);

            txtHoraInicial.setText("");
            txtHoraFinal.setText("");
        });

        cBoxUsuario.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxUsuario.isSelected();
            txtUsuario.setEnabled(enabled);
            txtUsuario.setText("");
        });
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBitacoraA = new javax.swing.JTable();
        paFiltrar = new javax.swing.JPanel();
        txtFechaFinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaInicial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHoraInicial = new javax.swing.JTextField();
        txtHoraFinal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cBoxFecha = new javax.swing.JCheckBox();
        cBoxHora = new javax.swing.JCheckBox();
        cBoxUsuario = new javax.swing.JCheckBox();
        txtUsuario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(980, 505));
        setLayout(null);

        tbBitacoraA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Hora", "Usuario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBitacoraA.setToolTipText("");
        tbBitacoraA.setColumnSelectionAllowed(true);
        tbBitacoraA.setPreferredSize(new java.awt.Dimension(578, 448));
        tbBitacoraA.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbBitacoraA);
        tbBitacoraA.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbBitacoraA.getColumnModel().getColumnCount() > 0) {
            tbBitacoraA.getColumnModel().getColumn(0).setResizable(false);
            tbBitacoraA.getColumnModel().getColumn(1).setResizable(false);
            tbBitacoraA.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(16, 41, 578, 448);

        paFiltrar.setBorder(javax.swing.BorderFactory.createTitledBorder("¿Filtrar?"));
        paFiltrar.setLayout(null);

        txtFechaFinal.setEnabled(false);
        txtFechaFinal.setPreferredSize(new java.awt.Dimension(30, 22));
        paFiltrar.add(txtFechaFinal);
        txtFechaFinal.setBounds(70, 105, 100, 27);

        jLabel1.setText("De:");
        paFiltrar.add(jLabel1);
        jLabel1.setBounds(17, 65, 17, 16);

        jLabel2.setText("Hasta:");
        paFiltrar.add(jLabel2);
        jLabel2.setBounds(16, 108, 33, 16);

        jLabel7.setText("De:");
        paFiltrar.add(jLabel7);
        jLabel7.setBounds(235, 65, 17, 16);

        txtFechaInicial.setEnabled(false);
        txtFechaInicial.setPreferredSize(new java.awt.Dimension(30, 22));
        paFiltrar.add(txtFechaInicial);
        txtFechaInicial.setBounds(71, 62, 100, 27);

        jLabel8.setText("Hasta:");
        paFiltrar.add(jLabel8);
        jLabel8.setBounds(234, 108, 33, 16);

        txtHoraInicial.setEnabled(false);
        txtHoraInicial.setPreferredSize(new java.awt.Dimension(50, 22));
        paFiltrar.add(txtHoraInicial);
        txtHoraInicial.setBounds(288, 62, 50, 27);

        txtHoraFinal.setEnabled(false);
        txtHoraFinal.setPreferredSize(new java.awt.Dimension(50, 22));
        paFiltrar.add(txtHoraFinal);
        txtHoraFinal.setBounds(288, 105, 50, 27);
        paFiltrar.add(jSeparator1);
        jSeparator1.setBounds(21, 147, 314, 10);

        cBoxFecha.setText("Fecha");
        paFiltrar.add(cBoxFecha);
        cBoxFecha.setBounds(17, 30, 54, 20);

        cBoxHora.setText("Hora");
        paFiltrar.add(cBoxHora);
        cBoxHora.setBounds(234, 30, 49, 20);

        cBoxUsuario.setText("Usuario");
        paFiltrar.add(cBoxUsuario);
        cBoxUsuario.setBounds(51, 176, 63, 20);

        txtUsuario.setEnabled(false);
        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 22));
        paFiltrar.add(txtUsuario);
        txtUsuario.setBounds(153, 174, 150, 27);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        paFiltrar.add(btnBuscar);
        btnBuscar.setBounds(102, 217, 150, 50);

        add(paFiltrar);
        paFiltrar.setBounds(610, 41, 354, 448);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox cBoxFecha;
    private javax.swing.JCheckBox cBoxHora;
    private javax.swing.JCheckBox cBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel paFiltrar;
    private javax.swing.JTable tbBitacoraA;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicial;
    private javax.swing.JTextField txtHoraFinal;
    private javax.swing.JTextField txtHoraInicial;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public RegistroAccesoBusquedaDTO obtenerCampos() {
        RegistroAccesoBusquedaDTO campos = new RegistroAccesoBusquedaDTO();
        
        campos.setFechaInicial(txtFechaInicial.getText());
        campos.setFechaFinal(txtFechaFinal.getText());
        campos.setHoraInicial(txtHoraInicial.getText());
        campos.setHoraFinal(txtHoraFinal.getText());
        campos.setUsuario(txtUsuario.getText());

        return campos;
    }

    @Override
    public void mostrarRegistros(List<? extends DTO> registros) {
        mostrarRegistrosEnTabla(tbBitacoraA, registros);
    }

}
