package com.enpresa.productadmin.vistas.gui;

import com.enpresa.productadmin.modelo.dto.DTO;
import com.enpresa.productadmin.modelo.dto.RegistroTransaccionBusquedaDTO;
import com.enpresa.productadmin.vistas.EntradaUsuario;
import com.enpresa.productadmin.vistas.MostrarRegistros;
import com.enpresa.productadmin.vistas.VistaGraficaConRegistros;
import java.awt.event.ActionEvent;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author Alejo
 */
public class BitacoraTransaccionesVista extends VistaGraficaConRegistros implements EntradaUsuario, MostrarRegistros {

    /**
     * Creates new form BitacoraAcceso
     */
    public BitacoraTransaccionesVista() {
        initComponents();
        agregarAlternadores();
    }

    private void agregarAlternadores() {
        cBoxFecha.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxFecha.isSelected();
            txtFechaInicial.setEnabled(enabled);
            txtFechaFinal.setEnabled(enabled);

            txtFechaInicial.setText("");
            txtFechaFinal.setText("");
        });

        cBoxHora.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxHora.isSelected();
            txtHoraInicial.setEnabled(enabled);
            txtHoraFinal.setEnabled(enabled);

            txtHoraInicial.setText("");
            txtHoraFinal.setText("");
        });

        cBoxObjeto.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxObjeto.isSelected();
            txtObjeto.setEnabled(enabled);
            txtObjeto.setText("");
        });

        cBoxUsuario.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxUsuario.isSelected();
            txtUsuario.setEnabled(enabled);
            txtUsuario.setText("");
        });

        cBoxAccion.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxAccion.isSelected();
            comboBoxAccion.setEnabled(enabled);
        });

        cBoxModulo.addActionListener((ActionEvent e) -> {
            boolean enabled = cBoxModulo.isSelected();
            comboBoxModulo.setEnabled(enabled);
        });
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    @Override
    public RegistroTransaccionBusquedaDTO obtenerCampos() {
        RegistroTransaccionBusquedaDTO campos = new RegistroTransaccionBusquedaDTO();
        campos.setFechaInicial(txtFechaInicial.getText());
        campos.setFechaFinal(txtFechaFinal.getText());
        campos.setHoraInicial(txtHoraInicial.getText());
        campos.setHoraFinal(txtHoraFinal.getText());
        campos.setObjeto(txtObjeto.getText());
        campos.setUsuario(txtUsuario.getText());
        if (comboBoxAccion.isEnabled()) {
            campos.setAccion(comboBoxAccion.getSelectedItem().toString());
        } else {
            campos.setAccion("");
        }
        if (comboBoxModulo.isEnabled()) {
            campos.setModulo(comboBoxModulo.getSelectedItem().toString());
        } else {
            campos.setModulo("");
        }

        return campos;
    }

    @Override
    public void mostrarRegistros(List<? extends DTO> registros) {
        mostrarRegistrosEnTabla(tbBitacoraTrans, registros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbBitacoraTrans = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtFechaFinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFechaInicial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtHoraInicial = new javax.swing.JTextField();
        txtHoraFinal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        cBoxFecha = new javax.swing.JCheckBox();
        cBoxHora = new javax.swing.JCheckBox();
        comboBoxModulo = new javax.swing.JComboBox<>();
        comboBoxAccion = new javax.swing.JComboBox<>();
        cBoxObjeto = new javax.swing.JCheckBox();
        txtUsuario = new javax.swing.JTextField();
        cBoxUsuario = new javax.swing.JCheckBox();
        cBoxAccion = new javax.swing.JCheckBox();
        cBoxModulo = new javax.swing.JCheckBox();
        txtObjeto = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(980, 505));
        setLayout(null);

        tbBitacoraTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Hora", "Objeto", "Usuario", "Acción", "Módulo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBitacoraTrans.setToolTipText("");
        tbBitacoraTrans.setColumnSelectionAllowed(true);
        tbBitacoraTrans.setPreferredSize(new java.awt.Dimension(578, 448));
        tbBitacoraTrans.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbBitacoraTrans);
        tbBitacoraTrans.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tbBitacoraTrans.getColumnModel().getColumnCount() > 0) {
            tbBitacoraTrans.getColumnModel().getColumn(0).setResizable(false);
            tbBitacoraTrans.getColumnModel().getColumn(1).setResizable(false);
            tbBitacoraTrans.getColumnModel().getColumn(2).setResizable(false);
            tbBitacoraTrans.getColumnModel().getColumn(3).setResizable(false);
            tbBitacoraTrans.getColumnModel().getColumn(4).setResizable(false);
            tbBitacoraTrans.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(16, 41, 578, 448);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("¿Filtrar?"));
        jPanel1.setLayout(null);

        txtFechaFinal.setEnabled(false);
        txtFechaFinal.setPreferredSize(new java.awt.Dimension(30, 22));
        jPanel1.add(txtFechaFinal);
        txtFechaFinal.setBounds(70, 105, 100, 27);

        jLabel1.setText("De:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(17, 65, 17, 16);

        jLabel2.setText("Hasta:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 108, 33, 16);

        jLabel7.setText("De:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(235, 65, 17, 16);

        txtFechaInicial.setEnabled(false);
        txtFechaInicial.setPreferredSize(new java.awt.Dimension(30, 22));
        jPanel1.add(txtFechaInicial);
        txtFechaInicial.setBounds(71, 62, 100, 27);

        jLabel8.setText("Hasta:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(234, 108, 33, 16);

        txtHoraInicial.setEnabled(false);
        txtHoraInicial.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel1.add(txtHoraInicial);
        txtHoraInicial.setBounds(288, 62, 50, 27);

        txtHoraFinal.setEnabled(false);
        txtHoraFinal.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel1.add(txtHoraFinal);
        txtHoraFinal.setBounds(288, 105, 50, 27);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(21, 147, 314, 10);

        cBoxFecha.setText("Fecha (yyyy-mm-dd)");
        jPanel1.add(cBoxFecha);
        cBoxFecha.setBounds(17, 30, 150, 20);

        cBoxHora.setText("Hora (hh:mm)");
        jPanel1.add(cBoxHora);
        cBoxHora.setBounds(234, 30, 100, 20);

        comboBoxModulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Productos", "Usuarios" }));
        comboBoxModulo.setEnabled(false);
        comboBoxModulo.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(comboBoxModulo);
        comboBoxModulo.setBounds(153, 305, 150, 27);

        comboBoxAccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crear", "Modificar", "Eliminar" }));
        comboBoxAccion.setEnabled(false);
        comboBoxAccion.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(comboBoxAccion);
        comboBoxAccion.setBounds(153, 262, 150, 27);

        cBoxObjeto.setText("Objeto");
        jPanel1.add(cBoxObjeto);
        cBoxObjeto.setBounds(51, 176, 59, 20);

        txtUsuario.setEnabled(false);
        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(153, 219, 150, 27);

        cBoxUsuario.setText("Usuario");
        jPanel1.add(cBoxUsuario);
        cBoxUsuario.setBounds(51, 221, 63, 20);

        cBoxAccion.setText("Accion");
        jPanel1.add(cBoxAccion);
        cBoxAccion.setBounds(51, 264, 60, 20);

        cBoxModulo.setText("Módulo");
        jPanel1.add(cBoxModulo);
        cBoxModulo.setBounds(51, 307, 65, 20);

        txtObjeto.setEnabled(false);
        txtObjeto.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(txtObjeto);
        txtObjeto.setBounds(153, 174, 150, 27);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(102, 348, 150, 50);

        add(jPanel1);
        jPanel1.setBounds(610, 41, 354, 448);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JCheckBox cBoxAccion;
    private javax.swing.JCheckBox cBoxFecha;
    private javax.swing.JCheckBox cBoxHora;
    private javax.swing.JCheckBox cBoxModulo;
    private javax.swing.JCheckBox cBoxObjeto;
    private javax.swing.JCheckBox cBoxUsuario;
    private javax.swing.JComboBox<String> comboBoxAccion;
    private javax.swing.JComboBox<String> comboBoxModulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbBitacoraTrans;
    private javax.swing.JTextField txtFechaFinal;
    private javax.swing.JTextField txtFechaInicial;
    private javax.swing.JTextField txtHoraFinal;
    private javax.swing.JTextField txtHoraInicial;
    private javax.swing.JTextField txtObjeto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
