package com.enpresa.productadmin.vistas.gui;

import com.enpresa.productadmin.modelo.dto.ClaveDTO;
import com.enpresa.productadmin.vistas.EntradaUsuario;
import com.enpresa.productadmin.vistas.MapearAccion;
import com.enpresa.productadmin.vistas.VistaGraficaConNotificador;
import java.awt.event.ActionEvent;
import java.util.function.Function;

/**
 *
 * @author jmdub
 */
public class CambiarClaveVista extends VistaGraficaConNotificador implements MapearAccion, EntradaUsuario {

    /**
     * Creates new form CambiarPassword
     */
    public CambiarClaveVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtClaveActual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClaveNueva = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClaveConfirmacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(523, 236));
        setMinimumSize(new java.awt.Dimension(523, 236));
        setPreferredSize(new java.awt.Dimension(523, 236));

        jLabel1.setText("Contraseña actual:");
        jLabel1.setPreferredSize(new java.awt.Dimension(111, 21));

        txtClaveActual.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel2.setText("Nueva contraseña:");
        jLabel2.setPreferredSize(new java.awt.Dimension(111, 21));

        txtClaveNueva.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel3.setText("Confirmar contraseña:");
        jLabel3.setPreferredSize(new java.awt.Dimension(131, 21));

        txtClaveConfirmacion.setPreferredSize(new java.awt.Dimension(200, 27));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html> <p>Las contraseñas deben tener como mínimo:  <br>     - 10 caracteres de longitud.  <br>     - Un número.  <br>     - Un carácter especial (!@#$, entre otros).</p> </html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel5.setMaximumSize(new java.awt.Dimension(275, 70));
        jLabel5.setMinimumSize(new java.awt.Dimension(275, 70));
        jLabel5.setPreferredSize(new java.awt.Dimension(275, 70));
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setPreferredSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClaveActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtClaveNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClaveConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtClaveActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtClaveNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtClaveConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtClaveActual;
    private javax.swing.JTextField txtClaveConfirmacion;
    private javax.swing.JTextField txtClaveNueva;
    // End of variables declaration//GEN-END:variables

    @Override
    public ClaveDTO obtenerCampos() {
        ClaveDTO campos = new ClaveDTO();
        campos.setClaveActual(txtClaveActual.getText());
        campos.setClaveNueva(txtClaveNueva.getText());
        campos.setClaveConfirmacion(txtClaveConfirmacion.getText());

        return campos;
    }

    @Override
    public void mapearAccion(String accion, Function funcion) {
        switch (accion) {
            case "Confirmar" -> {
                btnConfirmar.addActionListener((ActionEvent e) -> {
                    funcion.apply(null);
                });
            }
            default -> {
                mostrarError("Operacion no soportada.");
            }
        }
    }

}
