package com.enpresa.productadmin.vistas.gui;

import com.enpresa.productadmin.vistas.MapearAccion;
import com.enpresa.productadmin.vistas.VistaGraficaConNotificador;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 *
 * @author jmdub
 */
public class IniciarSesionVista extends VistaGraficaConNotificador implements MapearAccion {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesionVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(182, 212));
        setMinimumSize(new java.awt.Dimension(182, 212));
        setPreferredSize(new java.awt.Dimension(250, 300));
        setLayout(null);

        jLabel1.setText("Usuario:");
        jLabel1.setMaximumSize(new java.awt.Dimension(49, 21));
        jLabel1.setMinimumSize(new java.awt.Dimension(49, 21));
        jLabel1.setPreferredSize(new java.awt.Dimension(49, 21));
        add(jLabel1);
        jLabel1.setBounds(50, 75, 49, 21);

        txtUsuario.setMaximumSize(new java.awt.Dimension(150, 27));
        txtUsuario.setMinimumSize(new java.awt.Dimension(150, 27));
        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 27));
        add(txtUsuario);
        txtUsuario.setBounds(50, 96, 150, 27);

        jLabel2.setText("Contraseña:");
        jLabel2.setMaximumSize(new java.awt.Dimension(72, 21));
        jLabel2.setMinimumSize(new java.awt.Dimension(72, 21));
        jLabel2.setPreferredSize(new java.awt.Dimension(72, 21));
        add(jLabel2);
        jLabel2.setBounds(50, 139, 72, 21);

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setMaximumSize(new java.awt.Dimension(104, 27));
        btnIniciarSesion.setMinimumSize(new java.awt.Dimension(104, 27));
        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(104, 27));
        add(btnIniciarSesion);
        btnIniciarSesion.setBounds(73, 203, 104, 27);
        add(txtClave);
        txtClave.setBounds(50, 160, 150, 27);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public Map<String, String> getCampos() {
        Map<String, String> campos = new HashMap<>();
        campos.put("usuario", txtUsuario.getText());
        campos.put("clave", obtenerClave(txtClave.getPassword()));
        
        return campos;
    }
    
    @Override
    public void mapearAccion(String accion, Function funcion) {
        switch (accion) {
            case "Iniciar Sesion" -> {
                btnIniciarSesion.addActionListener((ActionEvent e) -> {
                    funcion.apply(null);
                });
            }
        }
    }
    
    private String obtenerClave(char[] clave) {
        String claveString = "";
        for (int i = 0; i < clave.length; i++) {
            claveString += clave[i];
            clave[i] = 0;
        }
        return claveString;
    }
}
