/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enpresa.productadmin.vistas.gui;

import javax.swing.JButton;

/**
 *
 * @author jmdub
 */
public class IniciarSesionVista extends javax.swing.JPanel {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesionVista() {
        initComponents();
    }

    public String getUsuario() {
        return txtUsuario.getText();
    }

    public String getClave() {
        return txtClave.getText();
    }

    public void setUsuario(String usuario) {
        this.txtUsuario.setText(usuario);
    }

    public void setClave(String clave) {
        this.txtClave.setText(clave);
    }

    public JButton getBtnIniciarSesion() {
        return btnIniciarSesion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setAlignmentY(0.0F);
        setMaximumSize(new java.awt.Dimension(182, 212));
        setMinimumSize(new java.awt.Dimension(182, 212));
        setPreferredSize(new java.awt.Dimension(182, 212));

        jLabel1.setText("Usuario");
        jLabel1.setMaximumSize(new java.awt.Dimension(49, 21));
        jLabel1.setMinimumSize(new java.awt.Dimension(49, 21));
        jLabel1.setPreferredSize(new java.awt.Dimension(49, 21));

        txtUsuario.setMaximumSize(new java.awt.Dimension(150, 27));
        txtUsuario.setMinimumSize(new java.awt.Dimension(150, 27));
        txtUsuario.setPreferredSize(new java.awt.Dimension(150, 27));

        jLabel2.setText("Contraseña");
        jLabel2.setMaximumSize(new java.awt.Dimension(72, 21));
        jLabel2.setMinimumSize(new java.awt.Dimension(72, 21));
        jLabel2.setPreferredSize(new java.awt.Dimension(72, 21));

        txtClave.setMaximumSize(new java.awt.Dimension(150, 27));
        txtClave.setMinimumSize(new java.awt.Dimension(150, 27));
        txtClave.setPreferredSize(new java.awt.Dimension(150, 27));

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setMaximumSize(new java.awt.Dimension(104, 27));
        btnIniciarSesion.setMinimumSize(new java.awt.Dimension(104, 27));
        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(104, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
